### PR TITLE
Updated index.js to work with node-canvas-v2

### PR DESCRIPTION
**Pull request by TheDropOne**

### CODE REVIEW

**Comment by lukechilds** [comment]
Thanks for putting this together.

Can you look at the failing tests?

**Comment by TheDropOne** [comment]
> Thanks for putting this together.
> 
> Can you look at the failing tests?

Yep, forget to update the major version of canvas dependency in package.json file. Plz check out that one #73 10/13 Tests passed correctly

**Comment by lukechilds** [comment]
Thanks, have replied on your new PR.

Also, just FYI, you don't need to create a new PR to make changes. You can just push to this branch and GitHub will update the PR.

**Comment by TheDropOne** [comment]
Oh, i've missed that branch and created a new one. I will be more attentive next time, thanks =)

**Comment by lukechilds** [comment]
Yah it's no problem, just letting you know ;)

**Pull request closed without merging**
