### PR TITLE
Fully updated and working

### PR DESCRIPTION
**Pull request by MarcGodard**
I updated all the dependencies. Got all the tests to pass. Included the image resizing PR as I like it.

I know there are better ways to rewrite this with the new libs, but I just wanted a working version.

### CODE REVIEW

**Comment by MarcGodard** [comment]
All tests pass locally. I assume the tests are failing because I am using a mac and mac image processing libs while this uses ubuntu. If you want me to make it pass, I can fix it in a couple days on my ubuntu box. Cheers.

**Comment by MarcGodard** [comment]
Ok, only JPEG OS issue seems to be left when dealing with quality. I will work on my ubuntu box Monday.

**Comment by MarcGodard** [comment]
Done waiting. I figure this project is dead, so made my own in npm.

**Comment by lukechilds** [comment]
Apologies for the delay and thanks for your work on this.

I was in a motorbike accident so was unavailable for a few weeks and then had a lot of work to catch up on.

I have a pretty huge GitHub backlog to work through.

I'm still limited with time due to other responsibilities and this package is not a priority for me so maybe your v2 version is the best option for now.

When I have more free time available in the future I would love to review your changes and merge them in.

Thanks again for your work.

**Comment by MarcGodard** [comment]
No problem, hope your accident wasn't that bad.

**Pull request closed without merging**
